document.write("    <aside class = \"left\">");
document.write("    <ul class = \"navigator\">");
document.write("    <li><a href = \"\">blog<\/a><\/li>");
document.write("    <li><a href = \"\">tutorials<\/a><span class=\"button\" id=\"button\">hi<\/span>");
document.write("      <ul id = \"hidden\">");
document.write("        <li><a href = \"\">Basic Concepts<\/a><\/li>");
document.write("        <li><a href = \"\">Resistive Circuits<\/a><\/li>");
document.write("        <li><a href = \"\">Nodal and Loop Analysis<\/a><\/li>");
document.write("        <li><a href = \"\">Op-Amps<\/a><\/li>");
document.write("        <li><a href = \"\">Additional Analysis<\/a><\/li>");
document.write("        <li><a href = \"\">Capacitance and Inductance<\/a><\/li>");
document.write("        <li><a href = \"\">First Order Transient Circuits<\/a><\/li>");
document.write("      <\/ul>    ");
document.write("    <\/li>");
document.write("    ");
document.write("    <li><a href = \"\">about<\/a><\/li>");
document.write("    <li><a href = \"\">tutoring<\/a><\/li>");
document.write("    <li><a href = \"\">resources<\/a><\/li>");
document.write("    ");
document.write("    <\/ul>");
document.write("    <\/aside>");
